### ISSUE TITLE
Publish to registry

### ISSUE THREAD

**Issue by montogeek** [smartvokat/esbuild-plugin-relay#1]
Hi!

I just found out that this package is not published in the registry: https://www.npmjs.com/package/esbuild-plugin-relay returns 404.

When can it be published?

Thanks!

**Comment by madebyherzblut** [comment]
Hey @montogeek thank you for submitting the bug report! I just published the current version, but be aware that we only use it as a research project internally–so it is highly experimental. Let me know when you encounter bugs 🙂
