### ISSUE TITLE
where would you import `graphql` from?

### ISSUE THREAD

**Issue by ryanblakeley** [smartvokat/esbuild-plugin-relay#4]
it seems like this package is a substitute for `babel-plugin-relay`, so that a project without babel can still run with relay. if so, how would you expect to import graphql, i.e. replace this line:

```
import graphql from 'babel-plugin-relay/macro';
```

when imported from react-relay

```
import {
  RelayEnvironmentProvider,
  loadQuery,
  usePreloadedQuery,
	graphql,
} from 'react-relay/hooks';
```

we see this error
![image](https://user-images.githubusercontent.com/3956993/146623758-449e9f92-28da-45cc-a680-142b03b6b4b0.png)

**Comment by madebyherzblut** [comment]
@rojobuffalo importing `graphql` from `react-relay/hooks` is the right way to go. This plugin will look for `graphql` and replace it with the compiled output. So, I assume the plugin never ran or there is something wrong with the detection. Can you show us your Vite config?
